### ISSUE TITLE
Crashing on drill selection

### ISSUE THREAD

**Issue by BruceNotLee** [Pointifix/AutoDrill#17]
First level of campaign, game crashes after selecting the direction of belts.

The mod 'AutoDrill' (auto-drill) has caused Mindustry to crash.
Version: bleeding-edge build 25369
OS: Windows 10 x64 (amd64)
Java Version: 11.0.12
Runtime Available Memory: 16376mb
Cores: 8
Likely Cause: AutoDrill (auto-drill v1)
Mods: auto-drill:1, auto-research:Algorithm 1.2

java.lang.NoSuchMethodError: 'arc.struct.Seq arc.struct.Seq.filter(arc.func.Boolf)'
	at autodrill.filler.BridgeDrill.placeDrillsAndBridges(BridgeDrill.java:32)
	at autodrill.filler.BridgeDrill.fill(BridgeDrill.java:26)
	at autodrill.AutoDrill.lambda$buildSelectTable$17(AutoDrill.java:197)
	at autodrill.AutoDrill.lambda$buildDirectionTable$28(AutoDrill.java:319)
	at arc.scene.Element.lambda$clicked$2(Element.java:913)
	at arc.scene.Element$4.clicked(Element.java:922)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:378)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:181)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:190)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by ProdDanny03** [comment]
updated arc.struct.Seq replaces .filter Constructor detail with .retainAll, if i get the mod working ill post it and send the link
![Screenshot 2024-11-11 002317](https://github.com/user-attachments/assets/941adcdf-a88c-46c4-8ef7-06c718dc2a11)

**Comment by ProdDanny03** [comment]
https://github.com/ProdDanny03/AutoDrillV2   this will work for now, download it and import (icon in top right corner is broken but the plugin is now fully functional
